### PR TITLE
turn on implicit casts, fix Page.reload

### PR DESCRIPTION
**Pull request by jakemac53**
Fixes https://github.com/google/webkit_inspection_protocol.dart/issues/44

I can separate out that change if you want (the bug fix), but imo its worth disabling the implicit casts entirely since they are not safe (as evidenced by the issue).

The only api change I believe is I changed `WipForwarder` to take a `Stream<String>` explicitly, instead of a `Stream<dynamic>`. I could change that to an internal cast but I think its better to express the required type explicitly.

### CODE REVIEW

**Comment by jakemac53** [comment]
cc @grouma

**Comment by devoncarew** [comment]
>I can separate out that change if you want (the bug fix), but imo its worth disabling the implicit casts entirely since they are not safe (as evidenced by the issue).

It's up to you - I think disabling the implicit casts is worthwhile (esp. as it would have caught the bug), but it's more to work through for this PR. 

> The only api change I believe is I changed WipForwarder to take a Stream<String> explicitly, instead of a Stream<dynamic>. I could change that to an internal cast but I think its better to express the required type explicitly.

I agree - I like the more explicit return type.

**Comment by jakemac53** [comment]
All maps from json are typed as `Map<String, dynamic>` (json only allows string keys). https://dartpad.dartlang.org/b1f6e4b2cd512191642548b293f0103e

**Comment by jakemac53** [comment]
I did also run the tests from the `dwds` and `webdev` packages which use this package and they are all fine (since the tests from this package don't seem to work right now)

**Comment by devoncarew** [comment]
> All maps from json are typed as `Map<String, dynamic>` (json only allows string keys). https://dartpad.dartlang.org/b1f6e4b2cd512191642548b293f0103e

Ah, good to know; lgtm then.

**Comment by jakemac53** [comment]
I can't merge but I don't have any further changes if you would like to :)

**Comment by devoncarew** [comment]
published as `0.4.1`

**Pull request merged**
